# Generated by Django 2.0.5 on 2018-11-29 10:33

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_remove_question_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_markdown.models.MarkdownField(verbose_name='填写答案'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='comment_text',
            field=django_markdown.models.MarkdownField(verbose_name='填写评论'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='comment_text',
            field=models.CharField(max_length=250, verbose_name='填写评论'),
        ),
    ]
